springBoot {
    mainClass = 'com.honeymorning.batch.BatchApplication'
}

bootJar {
    enabled = true
    archiveClassifier = 'boot'
}

jar {
    enabled = true
    archiveClassifier = ''
}


dependencies {
    implementation project(':common')

    testImplementation 'com.h2database:h2'

    // LOG
    implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.9.0'

    // BATCH
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    testImplementation 'org.springframework.batch:spring-batch-test'
}
