springBoot {
    mainClass = 'com.honeymorning.batch.BatchApplication'
}

// 실행 가능한 JAR 생성
bootJar {
    enabled = true
    archiveClassifier = 'boot'
}

jar {
    enabled = true
    archiveClassifier = ''
}


dependencies {
    implementation project(':common')
    runtimeOnly 'com.mysql:mysql-connector-j'

    // TEST CONTAINER
    // Test Container
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:localstack'
    testImplementation 'org.testcontainers:rabbitmq'
    testImplementation 'org.testcontainers:kafka'
    testImplementation 'org.testcontainers:mysql'
    testImplementation 'org.testcontainers:elasticsearch:1.19.8'
    testImplementation 'com.h2database:h2'
    
    // LOMBOK
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // BATCH
    implementation 'org.springframework.boot:spring-boot-starter-batch'

    // Spring Batch Test
    testImplementation 'org.springframework.batch:spring-batch-test'
}
