services:
  honeymorning_db:
    container_name: honeymorning_db
    image: mysql:8.0
    restart: unless-stopped
    mem_limit: "1g"
    cpus: "1.5"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: honeymorning
      MYSQL_USER: honeymorning
      MYSQL_PASSWORD: honeymorning
      TZ: Asia/Seoul
    volumes:
      - ./master-data:/var/lib/mysql
      - ./replication/master.cnf:/etc/mysql/conf.d/my.cnf
      - ./replication/master.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  honeymorning_read_only_db:
    container_name: honeymorning_read_only_db
    image: mysql:8.0
    restart: unless-stopped
    mem_limit: "1g"
    cpus: "1.5"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: honeymorning
      MYSQL_USER: honeymorning
      MYSQL_PASSWORD: honeymorning
      TZ: Asia/Seoul
    volumes:
      - ./slave-data:/var/lib/mysql
      - ./replication/slave.cnf:/etc/mysql/conf.d/my.cnf
      - ./replication/slave.sql:/tmp/slave.sql
      - ./replication/warming/seed.sql:/tmp/seed.sql
    ports:
      - "3308:3306"
    depends_on:
      honeymorning_db:
        condition: service_healthy
    command: >
      bash -c "
        docker-entrypoint.sh mysqld &
      
        until mysql -u root -proot -e 'SELECT 1'; do
          echo 'MySQL is unavailable - sleeping'
          sleep 1
        done
      
        mysql -uroot -proot < /tmp/slave.sql &&
      
        echo 'Replication complete.'
        wait
      "
  event-db:
    container_name: event-db
    image: mysql:8.0
    restart: unless-stopped
    mem_limit: "1g"
    cpus: "1.5"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event_store
      MYSQL_USER: honeymorning
      MYSQL_PASSWORD: honeymorning
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/event:/var/lib/mysql