version: "3.8"

services:
  rabbitmq-1:
    image: rabbitmq:4.0-management
    hostname: rabbitmq-1
    container_name: rabbitmq-1
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_NODENAME: rabbit@rabbitmq-1
      RABBITMQ_PROMETHEUS_EXPORTER: true
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins:ro

    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq-2:
    image: rabbitmq:4.0-management
    hostname: rabbitmq-2
    container_name: rabbitmq-2
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_NODENAME: rabbit@rabbitmq-2
      RABBITMQ_PROMETHEUS_EXPORTER: true
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins:ro

    depends_on:
      rabbitmq-1:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq-3:
    image: rabbitmq:4.0-management
    hostname: rabbitmq-3
    container_name: rabbitmq-3
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_NODENAME: rabbit@rabbitmq-3
      RABBITMQ_PROMETHEUS_EXPORTER: true
    ports:
      - "5674:5672"
      - "15674:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    depends_on:
      rabbitmq-1:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

  haproxy:
    image: haproxy:3.0
    hostname: haproxy
    container_name: rabbitmq-haproxy
    ports:
      - "5670:5672"
      - "15670:15672"
      - "1936:1936"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      rabbitmq-1:
        condition: service_healthy
      rabbitmq-2:
        condition: service_healthy
      rabbitmq-3:
        condition: service_healthy
