server:
  port: ${SERVER_PORT:8080}

spring:
  batch:
    jdbc:
      initialize-schema: always

  data:
    redis:
      host: ENC(Mdm3ZYu19EpQS7ZSZ1d/kKG8d/2RGVBy)
      port: ENC(u7qkh3ysOlEOXaVQlVJRdw==)
      connect-timeout: ENC(BR+NA152pLTvtizL5hBrxQ==)
      timeout: ENC(w952krjtcayAnH1nsIEiSw==)

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(xZDkAzthzyGE1C72KPqfJOuxhc3ayV4fQGZ5md/pzjIPv+QquUXpKEtB/7CVnaqkcxJf4XU/dTpDd3y6k5ntzbRuUN6SxC5Khjzl5MHLUpaWMV05G7qE4tzpLZ9C4GIlXDLPiIHQvif8u8N4H7L9hb6dKHPl08bS)
    username: ENC(4bVSlObkLOxikway4Ip0czodcbatpmA4)
    password: ENC(dP/YyZ2a7IEf5ybHgc357/iIDu8jAe1H)

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
      show-sql: false
    defer-datasource-initialization: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  rabbitmq:
    host: ENC(3c3rBT0e0I4eLxq2i7WQI3dQQP2m6izd)
    port: ENC(KgnOnUUSLJbB0N1rtgCfCA==)
    username: ENC(egHMI2wBoxjsFRgwodbrGw==)
    password: ENC(2oBor7W8ilV6FGD+BI7rdw==)
    publisher-returns: true

jwt:
  issuer: ENC(PazcZ21ocRNS74Kr3cHrkhdSjvfSCMzq)
  access-token:
    header: ENC(XXHVYj0tsPfymXbzxScERFFPhkiwf08S)
    expiry-seconds: ${ACCESS_EXPIRY_SECOND:ENC(TDrBoMkhMZrTt/cwfl0qug==)}
  refresh-token:
    header: ENC(qbKLojrcSZlXAfg3KyXmTuIKMrggnMzv)
    expiry-seconds: ${REFRESH_EXPIRY_SECOND:ENC(qgEqfPLe7Yv9XLDNhHpaIA==)}
  secret-key: ${SECRET_KEY:ENC(Puo2Y1vQGKk7B/xVoELd0yK63SxRUvnMf1NIew9jXXo=)}

web:
  cors:
    allowed-origins:
      - ENC(FUAQL1i0rUJejed6pnrQxK/Ax5PTUpr7wxzTQOLw+PI=)
      - ENC(LCEPAqi3qsGsegiqgzk9CI8yv+VaSzSBru8XOWBM0+n+nJK4+K8dFA==)
      - ENC(HEdYY0KD9C7eEER+Ma7h4K++mBc66RCVHhLc9/y1j54=)
      - ENC(6UqINXqO8U6UqkUAIgc71GemHdKAAR9hzMWp+ABL6LE=)
    allowed-methods:
      - ENC(G7ZLJaKSHLuKLIEgEhxClA==)
      - ENC(OMhFJ+01FoMZlyliLnz3bQ==)
      - ENC(ZZ3LCf1IGbXIdl8JaPF3Iw==)
      - ENC(RlYaFglzgIDnTCqQUqw4Uw==)
      - ENC(q/IeMV+hvW+iitIVRXfpQQ==)
      - ENC(SPetTvoUtSqpHEboxuh4xQ==)
    allowed-headers:
      - ENC(udJaeOPv6tro8S/PvD4b8Wfswl3W0qQC)
    exposed-headers:
      - ENC(zawNibKZ37XbuF99U1MuPgxupXbsepFL)
    allow-credentials: true

security:
  url-pattern:
    ignoring:
      GET:
        - ENC(c8vD1N66eJO/GxFSlgRXXKsMOL0+/84U)
        - ENC(UYACp25SidA7SyaRwTxQQ4iu58KbmgQc)
        - ENC(Jj5DshZnYbCcus185YtARn0yNrwecuFkLjfD1K6UgrI=)
        - ENC(0y1hnS8NwQvpq14+aB5Lpw==)
        - ENC(hkWrBlWf8qbdK0T0+jBcCDDOvCQ/H661)
      POST:
        - ENC(cX06x50vqq0M7qcxpQKaU64V8LvxkUDS1+L6lUl8PMQ=)
        - /api/accounts/login
      PATCH:
        - ENC(iv1dk6YjfwUZCP4o2mbeAi+RpQwpTAs5)
      PUT:
        - ENC(DDJCSLreDqSw9wmniZUkXJ9DPe7mz6ua)
      DELETE:
        - ENC(XoRy7x2VBG1Kg87v3PaSceQqYzDxkGfB)
    permit-all:
      GET: [ ]
      POST: [ ]
      PATCH: [ ]
      PUT: [ ]
      DELETE: [ ]
      OPTIONS: /**

aws:
  s3:
    client:
      access-key: ENC(CG2kGpzauXUGc5AMUfvIig==)
      secret-access-key: ENC(wL4ZBDG69Z9RL91aKTB1tQ==)
      region: ENC(CurWBvXC9t9keeApu2cA8ijLkS2X5AKN)
      endpoint: ENC(uksqy4TCBYybyBCR5WRV0ot/QLh2PzCRis98O0w7R7M=)
    bucket-name:
      tts: ENC(H+mJWwChPkcvjeQZ3dcNoO1yKYrHSy6H)
    domain-name: http://localhost:4566/${aws.s3.bucket-name.tts}

cookie:
  secure: ${COOKIE_SECURE:ENC(HDfUXBUpjV2TFLDs+cDo2w==)}
  same-site: ${COOKIE_SAME_SITE:ENC(lNIKQoe0yCJO8bYchDCtLA==)}
  domain: ${DOMAIN:ENC(8oopqns3PXQmdpHYwqvGLUEVS51gnVcm)}

ai:
  client:
    brief: ENC(Vctnoxd7vvLZNQJA/9gTYU+bU9224Z0LJCErqOvPnLApiFHsT5Eh61/8Bt1sglkk)
    quiz: ENC(iPGCMk5OuYjylnz/P5pTfVFmXM4x5fNHrpQcpq9QzykcUr7Ti8IbhA==)
    song: ENC(Ihp/8Uz6a3eoBaagYUxdW7Uv2g58fo9K/x9jJwM/eXuKvEdEqFiswAIO2i79z6ZE)
    topic-model: ENC(K37CfhnlVJ4Z2ruV7bR8UG+v2+x+Ee9yNAqPCRrTAHCouTtuU/nrqAd2ApocmUyN)

voice:
  client:
    base-url: https://api.elevenlabs.io/v1
    resources:
      path:
        voice-id: ENC(oHL4IVSptV/dsyyaECzXqmx3baTxkpoPMjHebyvc7Mo=)
      header:
        optimize-streaming-Latency: ENC(xLq4jskZeNScCloU837EDw==)
        output_format: ENC(uINyBGA1XRBMmMkN3xFB+IuQlB2rRMuI)
        xi-api-key: ENC(fq1nxPppj0fKrnCxz4wdgzxTo+jaIIf9q86P1f3HOKKQQyNvwey4+L4swVM1xJPb5iX4zyepGNQWW50m2QBE1g==)
      body:
        model-id: ENC(PVI3+2C/nWQQBn57xf04LUN2FyAUxfj1xF7wxqnS3S4=)
        stability: ENC(2Hzak7m4jLw/Ph5NWJUMxg==)
        similarity-boost: ENC(pvPpTDNrUfWqRdPLTeupyw==)
        style: ENC(jOPHWrXge1pLxMbfVMaS0Q==)

file:
  directory:
    path:
      content: ENC(2HQTjTbC8xySkIgz6ktS4Y5VzA+5D3cKxew9VXunOGnHCMk8LlTX4zVS4YPu1fbqAZTxdFxKVWA=)
      summary: ENC(Cj301Z07a9MFTvutszAHTDpTgPDHSJC2FFKmTQu1a5nFEf0BlmdvbGltFp9AYa58yzW7CPYGSkg=)
      quiz: ENC(zW3TcGnHTLX5Na1Q3LeYkp9doE1F3u5L1bYSvUtrSKq4IJ/Q2OkM3+R/f0Epggu6xFtRksKPShs=)
      music: ENC(v8uwAbdOo/41AGKIKDSi5a+Po/vYAzWFHpkoQZhfD82FFaqcqGotm77x51dnvEGedxAxdkmFRPI=)

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  endpoint:
    prometheus:
      enabled: true
  metrics:
    enable:
      all: true

logging:
  level:
    root: info
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE