services:
  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: honeymorning
      MYSQL_USER: honeymorning
      MYSQL_PASSWORD: honeymorning
      TZ: Asia/Seoul
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2
    container_name: redis
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
    ports:
      - "6379:6379"
    command: [
      "redis-server",
      "--requirepass", "$REDIS_PASSWORD",
      "--appendonly", "yes",
      "--appendfilename", "appendonly.aof",
      "--appendfsync", "everysec",
      "--save", "900 1",
      "--save", "300 10",
      "--save", "60 10000",
      "--maxmemory", "512mb",
      "--maxmemory-policy", "allkeys-lru",
      "--tcp-keepalive", "300",
      "--loglevel", "notice"
    ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    
        max-file: "3"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_ui
    restart: unless-stopped
    environment:
      REDIS_HOSTS: "local:redis:6379"
      REDIS_PASSWORD: redis_password
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis_data: