version: "3.8"

services:
  mysql:
    extends:
      file: local/mysql/mysql.yml
      service: mysql

  event-db:
    extends:
      file: local/mysql/mysql.yml
      service: event-db

  redis:
    extends:
      file: ../relay/src/main/resources/infra/redis/redis.yml
      service: redis

  rabbitmq-1:
    extends:
      file: ../relay/src/main/resources/infra/rabbitmq/rabbitmq.yml
      service: rabbitmq-1

  rabbitmq-2:
    extends:
      file: ../relay/src/main/resources/infra/rabbitmq/rabbitmq.yml
      service: rabbitmq-2

  rabbitmq-3:
    extends:
      file: ../relay/src/main/resources/infra/rabbitmq/rabbitmq.yml
      service: rabbitmq-3

  rabbitmq-haproxy:
    extends:
      file: ../relay/src/main/resources/infra/rabbitmq/rabbitmq.yml
      service: haproxy

  localstack:
    extends:
      file: ../relay/src/main/resources/infra/localstack/localstack.yml
      service: localstack

  prometheus:
    extends:
      file: ../relay/src/main/resources/infra/monitoring/monitoring.yml
      service: prometheus

  grafana:
    extends:
      file: ../relay/src/main/resources/infra/monitoring/monitoring.yml
      service: grafana

  kafka-1:
    extends:
      file: ../relay/src/main/resources/infra/cdc/cdc.yml
      service: kafka-1
  kafka-2:
    extends:
      file: ../relay/src/main/resources/infra/cdc/cdc.yml
      service: kafka-2
  kafka-3:
    extends:
      file: ../relay/src/main/resources/infra/cdc/cdc.yml
      service: kafka-3

  kafka-connect:
    extends:
      file: ../relay/src/main/resources/infra/cdc/cdc.yml
      service: kafka-connect

  kafka-ui:
    extends:
      file: ../relay/src/main/resources/infra/cdc/cdc.yml
      service: kafka-ui

  elasticsearch:
    extends:
      file: ./local/search/search.yml
      service: elasticsearch

  kibana:
    extends:
      file: ./local/search/search.yml
      service: kibana