version: "3.8"

services:
  mysql:
    extends:
      file: local/mysql/mysql.yml
      service: mysql

  redis:
    extends:
      file: local/redis/redis.yml
      service: redis

  rabbitmq:
    extends:
      file: local/rabbitmq/rabbitmq.yml
      service: rabbitmq

  localstack:
    extends:
      file: local/localstack/localstack.yml
      service: localstack

  prometheus:
    extends:
      file: local/monitoring/monitoring.yml
      service: prometheus

  grafana:
    extends:
      file: local/monitoring/monitoring.yml
      service: grafana

  zookeeper:
    extends:
      file: ./local/cdc/cdc.yml
      service: zookeeper

  kafka:
    extends:
      file: ./local/cdc/cdc.yml
      service: kafka

  kafka-connect:
    extends:
      file: ./local/cdc/cdc.yml
      service: kafka-connect

  kafka-ui:
    extends:
      file: ./local/cdc/cdc.yml
      service: kafka-ui

  elasticsearch:
    extends:
      file: ./local/search/search.yml
      service: elasticsearch

  kibana:
    extends:
      file: ./local/search/search.yml
      service: kibana