server:
  port: ${SERVER_PORT:8080}

spring:
  task:
    scheduling:
      pool:
        size: 5

  batch:
    job:
      enabled: false

  datasource:
    primary:
      url: ENC(5bTpOVwxt9brEY31eEcwVQ4ZokiFFIkS1vIsV2V5BwUe9cuDj+mdIxGnKtC0rMfM)
      username: ENC(4bVSlObkLOxikway4Ip0czodcbatpmA4)
      password: ENC(dP/YyZ2a7IEf5ybHgc357/iIDu8jAe1H)
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 10
        maximum-pool-size: 10
        max-lifetime: 25200000
        idle-timeout: 1800000
        connection-timeout: 3000
        validation-timeout: 5000

    read:
      url: ENC(fvY+b0P6S9DMldbaXHV4H/sRaCkOayzB7seXoZIFdc4yoBpepu5wy8Nx5ey952gMAnIsUC30WHdOKNURQbP5GWf4QUIHW+qEvrCPf/BIsCVpU8LVD6nSCz4D9XuT+auwJjL1piaMzc3Ha7UpGqdLjWNzZ3257/aA)
      username: ENC(HrXN/yuXf+kntxje8zkgow==)
      password: ENC(kPuHNfwdp3HsSbnZ97SBKw==)
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
      show-sql: false
    defer-datasource-initialization: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}

decorator:
  datasource:
    p6spy:
      log-format: "⏱️ %(executionTime)ms | %(sql)"
