server:
  port: ${SERVER_PORT:8080}

spring:

  batch:
    job:
      enabled: false

  datasource:
    primary:
      url: ENC(lGmkCTsQmhQYQWCog8DCV4AqcYBZ8+iMqW8KEd/uVyLkMk3vDYPLijof+HR80FdOv8Tt6dOUNsf0VARID8LlSOHpOnu1Ro7Cwp5a+NhOsdDLHZE4giOXJyZmHsrzB5gOn86LqQqPBdhMiD5vYo4M5vdT8Q4w7eFr)
      username: ENC(DQXodHYd1jH1HYKZ5BtsFL7Lwmz/L/NC)
      password: ENC(5y4OtO63K071suNPr2wpDsDsL8yV3uAH)
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 15
        maximum-pool-size: 25
        max-lifetime: 1800000
        idle-timeout: 600000
        connection-timeout: 3000
        validation-timeout: 5000

    read:
      url: ENC(h1+PiPu27kqM5c8HNEDPU62VnBKNEhLRsea3zEtGbOGg4XECsY/skJwYFspj5fRcOUo/xZYy2KjOX3e1LAb6F3dlvKXdOkMb)
      username: ENC(Pwrn0qav8Noba25RRDVmfQ==)
      password: ENC(C5CuK5SA7zL+LGzr00i6Mg==)
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 10
        maximum-pool-size: 15
        max-lifetime: 1800000
        idle-timeout: 600000
        connection-timeout: 3000
        validation-timeout: 5000

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
      show-sql: false
    defer-datasource-initialization: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}

decorator:
  datasource:
    p6spy:
      log-format: "⏱️ %(executionTime)ms | %(sql)"
