global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'rabbitmq:15692'

  - job_name: 'application'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080'